mime-type validator implemented and tested not to show in preview non-image files; Error TS2531 object is possibly null in angular reactive forms occured and resolved by using  the safe navigation operator ? into ngIf directive.